{"name": "Ошибка при попытке повторного создания существующего пользователя", "status": "passed", "start": 1717593102372, "stop": 1717593102784, "uuid": "25056283-e292-4902-b5af-c66191a32afb", "historyId": "c1e9f38a3f3f2563cf68ba2e3b34a03c", "testCaseId": "c1e9f38a3f3f2563cf68ba2e3b34a03c", "fullName": "tests.py.test_user.TestUserCreating#test_register_double_user_failed_result", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserCreating"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "18104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_user"}]}