{"name": "Ошибка при проверке пользователя с некорректным логином", "status": "passed", "start": 1717767620433, "stop": 1717767620711, "uuid": "4ca51f86-8ec9-47b2-a2c3-06b1b28cd2ac", "historyId": "242fd231cbb2ec66117d59ad53bd094e", "testCaseId": "242fd231cbb2ec66117d59ad53bd094e", "fullName": "tests.py.test_user.TestUserLogin#test_login_incorrect_email_failed_result", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "16524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_user"}]}