{"name": "Ошибка проверки получения заказов неавторизованного пользователя", "status": "passed", "start": 1717593119031, "stop": 1717593119307, "uuid": "5e9d1d14-56c7-4716-a40e-df75ab0e1805", "historyId": "d0d83c542eb38254b7c5f74c8c73a886", "testCaseId": "d0d83c542eb38254b7c5f74c8c73a886", "fullName": "tests.py.test_user.TestUserOrderGetting#test_getting_order_unauthorized_user", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserOrderGetting"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "18104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_user"}]}