{"name": "Ошибка при проверке пользователя с некорректным логином", "status": "passed", "start": 1717592838489, "stop": 1717592838759, "uuid": "7d9bfb89-0bae-44e4-80d4-27776aea45bc", "historyId": "242fd231cbb2ec66117d59ad53bd094e", "testCaseId": "242fd231cbb2ec66117d59ad53bd094e", "fullName": "tests.py.test_user.TestUserLogin#test_login_incorrect_email_failed_result", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "6544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_user"}]}